import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],

  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "!./app/privacy-policy/**/*.{js,ts,jsx,tsx,mdx}",
    "./presentation-templates/**/*.{js,ts,jsx,tsx,mdx}",
  ],

  safelist: [
    // Layout variant classes - dynamically generated by LLM for Smart Suggestions
    // These classes are injected via innerHTML so must be safelisted
    {
      pattern: /^(grid|flex|space-y-)/, // Match grid*, flex*, space-y-*
      variants: ['sm', 'md', 'lg', 'xl', '2xl'],
    },
    {
      pattern: /^grid-cols-/, // Match grid-cols-2, grid-cols-3, etc.
      variants: ['sm', 'md', 'lg', 'xl', '2xl'],
    },
    {
      pattern: /^gap-/, // Match gap-2, gap-4, gap-6, etc.
      variants: ['sm', 'md', 'lg', 'xl', '2xl'],
    },
    // Specific layout classes used by layout variants
    'grid', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4',
    'flex', 'flex-row', 'flex-col', 'flex-wrap',
    'space-y-2', 'space-y-4', 'space-y-6', 'space-y-8',
    'gap-2', 'gap-4', 'gap-6', 'gap-8',
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      fontFamily: {
        instrument_sans: ["var(--font-instrument-sans)"],
        inter: ["var(--font-inter)"],
        roboto: ["var(--font-roboto)"],
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("@tailwindcss/typography"),
  ],
};
export default config;
